---
- hosts: all
  become: true
  pre_tasks:

  - name: Update repo cache (Fedora)
    tags: always
    dnf:
      update_cache: true
    changed_when: false
    when: ansible_distribution == "Fedora"

  - name: Update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: true
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  tasks:

  - name: Add ssh key for admin
    tags: always
    authorized_key:
      user: admin
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEP0Dh4gujpNqCWK0wnthM5zOvwy/vvg/6llZEzFSI3X ansible"


- hosts: web_servers
  become: true
  tasks:

  - name: Install apache2 server package (Ubuntu)
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install apache2 server package (Fedora)
    tags: apache,httpd,fedora
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"
  
  - name: Start httpd (Fedora)
    tags: apache,httpd,fedora
    service:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == "Fedora"

  - name: Change e-mail adress for admin (Fedora)
    tags: apache,httpd,fedora
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin something@somewhere.pl
    when: ansible_distribution == "Fedora"
    register: httpd

  - name: Restart httpd (Fedora)
    tags: apache,httpd,fedora
    service:
      name: httpd
      state: restarted
    when: httpd.changed
  - name: Copy default html file for site
    tags: apache, apache, ubuntu
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:
  
  - name: Install MariaDB package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install MariaDB package (Fedora)
    tags: db,mariadb,fedora
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Fedora"

      
- hosts: file_servers
  become: true
  tasks:

    - name: Install Samba package (Fedora)
      tags: samba,fedora
      package: 
        name: samba
        state: latest
