- name: Install apache and php package (Ubuntu)
  tags: apache,php,ubuntu
  apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install apache and php package (Fedora)
  tags: apache,httpd,php,fedora
  dnf:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution == "Fedora"

- name: Start end enable apache service (Ubuntu)
  tags: apache,ubuntu
  systemd:
    name: apache2
    state: started
    enabled: true
  when: ansible_distribution == "Ubuntu"

- name: Start end enable apache service (Fedora)
  tags: apache,httpd.fedora
  systemd:
    name: httpd
    state: started
    enabled: true
  when: ansible_distribution == "Fedora"

- name: Change e-mail adress for admin (Fedora)
  tags: apache,httpd,fedora
  lineinfile: 
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin apache@pietryszak.pl
  when: ansible_distribution == "Fedora"
  register: httpd

- name: Restart httpd
  tags: apache,httpd
  service:
    name: "{{ apache_service }}"
    state: restarted
  when: httpd.changed

- name: Copy default html file for site
  tags: apache, apache, ubuntu
  copy: 
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
