- name: Install MariaDB package (Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install MariaDB package (Fedora)
  tags: db,mariadb,fedora
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "Fedora"
